### ISSUE TITLE
Release request :)

### ISSUE THREAD

**Issue by mpedrummer** [jakoch/PHPTracRPC#21]
Hey @jakoch - when you release next, can you release 7d71470 (https://github.com/jakoch/PHPTracRPC/commit/7d7147034d5dfe7384a5c0210bb6fb0e2c461203) as 1.0.2 before releasing the rest as 1.0.3?  That would simplify my testing procedure for implementation/rollout.

Looks like you've had a busy weekend :)

**Comment by jakoch** [comment]
Hey Tim! 
Ok - i will tag two new versions.

**Comment by jakoch** [comment]
Both versions are tagged now and Packagist was automatically updated.
https://packagist.org/packages/jakoch/php-trac-rpc#v1.0.2 - 7d71470
https://packagist.org/packages/jakoch/php-trac-rpc#v1.0.3 - 3c33db9
Closing.

**Comment by mpedrummer** [comment]
Thanks!  I'll switch to 1.0.2 now, and hopefully be able to test 1.0.3 later this week.
